### ISSUE TITLE
Repository is huge

### ISSUE THREAD

**Issue by hunse** [xchoo/spaun2.0#1]
I don't mean to complain, but having all the data files in the repository means that it's huge. Partly because they're just large, and partly because when they're changed, git stores the old version too. These files should really be on figshare (I've got code for downloading the MNIST data and the augmented Spaun symbols, see [here](https://github.com/hunse/mnist-nengo/blob/master/mnist.py)).

**Comment by xchoo** [comment]
Oh yeah. I should address this. :smile: 
I'll have to ask Trevor how to permanently delete stuff from github.

**Comment by jgosmann** [comment]
Here's a GitHub guide on how to do this: https://help.github.com/articles/remove-sensitive-data/

**Comment by xchoo** [comment]
I've already done this to the repo. The current size is because of the new vision data files (essentially a pkl of the vision network) for the lif convnet network.

**Comment by jgosmann** [comment]
Maybe you should close the issue? It's just 25MB at the moment. That doesn't seem too bad.
