### ISSUE TITLE
Conflict with `Network.n_neurons` property

### ISSUE THREAD

**Issue by drasmuss** [xchoo/spaun2.0#9]
https://github.com/nengo/nengo/commit/e6a830424351df663657a80eeb88c25c46f71bd8 added an `n_neurons` property to Networks, which conflicts with some places in Spaun where data was being stored in a `self.n_neurons` attribute (e.g., https://github.com/xchoo/spaun2.0/blob/9bb87ad0dae72f01c6ee36288e11dd19b4798b51/_spaun/_networks/workingmemory.py#L167).  This causes an error when Spaun tries to write to that property (since it is read-only).

**Comment by xchoo** [comment]
Fixed with 43d615cccc8877a27b9d5eb90111a631f5828898
